spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://120.79.169.125:3306/SpringCloud_Sell_OrderInfo?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '110110@Lv'
  jpa:
    show-sql: true
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8762/eureka/
server:
  port: 8011
env:
  test-test
prety:
  name: marue
  age: 9
