spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 110110@Lv
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  dev
